using System.Globalization;
using System.Resources;

namespace CamfrogMultiID.App;

/// <summary>Localized UI strings (Strings.resx default, Strings.th.resx). Missing entries fall back to the key name.</summary>
public static class Strings
{
    private static readonly ResourceManager Manager = new("CamfrogMultiID.App.Strings", typeof(Strings).Assembly);

    public static string MainTitle => Manager.GetString("MainTitle", CultureInfo.CurrentUICulture) ?? "MainTitle";
    public static string AddAccount => Manager.GetString("AddAccount", CultureInfo.CurrentUICulture) ?? "AddAccount";
    public static string Edit => Manager.GetString("Edit", CultureInfo.CurrentUICulture) ?? "Edit";
    public static string Delete => Manager.GetString("Delete", CultureInfo.CurrentUICulture) ?? "Delete";
    public static string EnableDisable => Manager.GetString("EnableDisable", CultureInfo.CurrentUICulture) ?? "EnableDisable";
    public static string Settings => Manager.GetString("Settings", CultureInfo.CurrentUICulture) ?? "Settings";
    public static string StartSelected => Manager.GetString("StartSelected", CultureInfo.CurrentUICulture) ?? "StartSelected";
    public static string StopSelected => Manager.GetString("StopSelected", CultureInfo.CurrentUICulture) ?? "StopSelected";
    public static string StartAll => Manager.GetString("StartAll", CultureInfo.CurrentUICulture) ?? "StartAll";
    public static string StopAll => Manager.GetString("StopAll", CultureInfo.CurrentUICulture) ?? "StopAll";
    public static string Refresh => Manager.GetString("Refresh", CultureInfo.CurrentUICulture) ?? "Refresh";
    public static string Search => Manager.GetString("Search", CultureInfo.CurrentUICulture) ?? "Search";
    public static string ColId => Manager.GetString("ColId", CultureInfo.CurrentUICulture) ?? "ColId";
    public static string ColAccount => Manager.GetString("ColAccount", CultureInfo.CurrentUICulture) ?? "ColAccount";
    public static string ColUsername => Manager.GetString("ColUsername", CultureInfo.CurrentUICulture) ?? "ColUsername";
    public static string ColEnabled => Manager.GetString("ColEnabled", CultureInfo.CurrentUICulture) ?? "ColEnabled";
    public static string ColStatus => Manager.GetString("ColStatus", CultureInfo.CurrentUICulture) ?? "ColStatus";
    public static string ColPid => Manager.GetString("ColPid", CultureInfo.CurrentUICulture) ?? "ColPid";
    public static string ColStarted => Manager.GetString("ColStarted", CultureInfo.CurrentUICulture) ?? "ColStarted";
    public static string ColError => Manager.GetString("ColError", CultureInfo.CurrentUICulture) ?? "ColError";
    public static string SelectedAccount => Manager.GetString("SelectedAccount", CultureInfo.CurrentUICulture) ?? "SelectedAccount";
    public static string ApplicationLog => Manager.GetString("ApplicationLog", CultureInfo.CurrentUICulture) ?? "ApplicationLog";
    public static string Level => Manager.GetString("Level", CultureInfo.CurrentUICulture) ?? "Level";
    public static string AutoScroll => Manager.GetString("AutoScroll", CultureInfo.CurrentUICulture) ?? "AutoScroll";
    public static string ClearLogView => Manager.GetString("ClearLogView", CultureInfo.CurrentUICulture) ?? "ClearLogView";
    public static string ExportLog => Manager.GetString("ExportLog", CultureInfo.CurrentUICulture) ?? "ExportLog";
    public static string Diagnostics => Manager.GetString("Diagnostics", CultureInfo.CurrentUICulture) ?? "Diagnostics";
    public static string OpenLogFolder => Manager.GetString("OpenLogFolder", CultureInfo.CurrentUICulture) ?? "OpenLogFolder";
    public static string CtxStart => Manager.GetString("CtxStart", CultureInfo.CurrentUICulture) ?? "CtxStart";
    public static string CtxStop => Manager.GetString("CtxStop", CultureInfo.CurrentUICulture) ?? "CtxStop";
    public static string CtxChangePassword => Manager.GetString("CtxChangePassword", CultureInfo.CurrentUICulture) ?? "CtxChangePassword";
    public static string CtxClearError => Manager.GetString("CtxClearError", CultureInfo.CurrentUICulture) ?? "CtxClearError";
    public static string AddAccountTitle => Manager.GetString("AddAccountTitle", CultureInfo.CurrentUICulture) ?? "AddAccountTitle";
    public static string DisplayName => Manager.GetString("DisplayName", CultureInfo.CurrentUICulture) ?? "DisplayName";
    public static string Username => Manager.GetString("Username", CultureInfo.CurrentUICulture) ?? "Username";
    public static string Password => Manager.GetString("Password", CultureInfo.CurrentUICulture) ?? "Password";
    public static string NewPasswordTitle => Manager.GetString("NewPasswordTitle", CultureInfo.CurrentUICulture) ?? "NewPasswordTitle";
    public static string PasswordHintAdd => Manager.GetString("PasswordHintAdd", CultureInfo.CurrentUICulture) ?? "PasswordHintAdd";
    public static string PasswordHintEdit => Manager.GetString("PasswordHintEdit", CultureInfo.CurrentUICulture) ?? "PasswordHintEdit";
    public static string RoomUrlLabel => Manager.GetString("RoomUrlLabel", CultureInfo.CurrentUICulture) ?? "RoomUrlLabel";
    public static string RoomUrlHint => Manager.GetString("RoomUrlHint", CultureInfo.CurrentUICulture) ?? "RoomUrlHint";
    public static string Enabled => Manager.GetString("Enabled", CultureInfo.CurrentUICulture) ?? "Enabled";
    public static string AutoRestartLabel => Manager.GetString("AutoRestartLabel", CultureInfo.CurrentUICulture) ?? "AutoRestartLabel";
    public static string Cancel => Manager.GetString("Cancel", CultureInfo.CurrentUICulture) ?? "Cancel";
    public static string Save => Manager.GetString("Save", CultureInfo.CurrentUICulture) ?? "Save";
    public static string SettingsTitle => Manager.GetString("SettingsTitle", CultureInfo.CurrentUICulture) ?? "SettingsTitle";
    public static string ClientExecutable => Manager.GetString("ClientExecutable", CultureInfo.CurrentUICulture) ?? "ClientExecutable";
    public static string Browse => Manager.GetString("Browse", CultureInfo.CurrentUICulture) ?? "Browse";
    public static string ArgsTemplate => Manager.GetString("ArgsTemplate", CultureInfo.CurrentUICulture) ?? "ArgsTemplate";
    public static string ArgsHint => Manager.GetString("ArgsHint", CultureInfo.CurrentUICulture) ?? "ArgsHint";
    public static string SandboxLabel => Manager.GetString("SandboxLabel", CultureInfo.CurrentUICulture) ?? "SandboxLabel";
    public static string SandboxExeLabel => Manager.GetString("SandboxExeLabel", CultureInfo.CurrentUICulture) ?? "SandboxExeLabel";
    public static string DownloadSandboxie => Manager.GetString("DownloadSandboxie", CultureInfo.CurrentUICulture) ?? "DownloadSandboxie";
    public static string CreateBoxes => Manager.GetString("CreateBoxes", CultureInfo.CurrentUICulture) ?? "CreateBoxes";
    public static string AutoBackupEvery => Manager.GetString("AutoBackupEvery", CultureInfo.CurrentUICulture) ?? "AutoBackupEvery";
    public static string DaysOffHint => Manager.GetString("DaysOffHint", CultureInfo.CurrentUICulture) ?? "DaysOffHint";
    public static string Files => Manager.GetString("Files", CultureInfo.CurrentUICulture) ?? "Files";
    public static string OpenDataFolder => Manager.GetString("OpenDataFolder", CultureInfo.CurrentUICulture) ?? "OpenDataFolder";
    public static string BackupData => Manager.GetString("BackupData", CultureInfo.CurrentUICulture) ?? "BackupData";
    public static string RestoreData => Manager.GetString("RestoreData", CultureInfo.CurrentUICulture) ?? "RestoreData";
    public static string Language => Manager.GetString("Language", CultureInfo.CurrentUICulture) ?? "Language";
    public static string ChangePasswordTitle => Manager.GetString("ChangePasswordTitle", CultureInfo.CurrentUICulture) ?? "ChangePasswordTitle";
    public static string NewPassword => Manager.GetString("NewPassword", CultureInfo.CurrentUICulture) ?? "NewPassword";
    public static string ChangePasswordHint => Manager.GetString("ChangePasswordHint", CultureInfo.CurrentUICulture) ?? "ChangePasswordHint";
    public static string MsgSelectAccount => Manager.GetString("MsgSelectAccount", CultureInfo.CurrentUICulture) ?? "MsgSelectAccount";
    public static string TitleEditAccount => Manager.GetString("TitleEditAccount", CultureInfo.CurrentUICulture) ?? "TitleEditAccount";
    public static string TitleDeleteAccount => Manager.GetString("TitleDeleteAccount", CultureInfo.CurrentUICulture) ?? "TitleDeleteAccount";
    public static string TitleEnableDisable => Manager.GetString("TitleEnableDisable", CultureInfo.CurrentUICulture) ?? "TitleEnableDisable";
    public static string TitleStartAccount => Manager.GetString("TitleStartAccount", CultureInfo.CurrentUICulture) ?? "TitleStartAccount";
    public static string TitleStopAccount => Manager.GetString("TitleStopAccount", CultureInfo.CurrentUICulture) ?? "TitleStopAccount";
    public static string TitleStartAll => Manager.GetString("TitleStartAll", CultureInfo.CurrentUICulture) ?? "TitleStartAll";
    public static string TitleStopAll => Manager.GetString("TitleStopAll", CultureInfo.CurrentUICulture) ?? "TitleStopAll";
    public static string TitleClearError => Manager.GetString("TitleClearError", CultureInfo.CurrentUICulture) ?? "TitleClearError";
    public static string TitleChangePassword => Manager.GetString("TitleChangePassword", CultureInfo.CurrentUICulture) ?? "TitleChangePassword";
    public static string TitleValidation => Manager.GetString("TitleValidation", CultureInfo.CurrentUICulture) ?? "TitleValidation";
    public static string TitleSaveError => Manager.GetString("TitleSaveError", CultureInfo.CurrentUICulture) ?? "TitleSaveError";
    public static string TitleStartError => Manager.GetString("TitleStartError", CultureInfo.CurrentUICulture) ?? "TitleStartError";
    public static string TitleStopError => Manager.GetString("TitleStopError", CultureInfo.CurrentUICulture) ?? "TitleStopError";
    public static string TitleUpdateError => Manager.GetString("TitleUpdateError", CultureInfo.CurrentUICulture) ?? "TitleUpdateError";
    public static string TitleDeleteError => Manager.GetString("TitleDeleteError", CultureInfo.CurrentUICulture) ?? "TitleDeleteError";
    public static string MsgEnterDisplayName => Manager.GetString("MsgEnterDisplayName", CultureInfo.CurrentUICulture) ?? "MsgEnterDisplayName";
    public static string MsgDisplayNameTooLong => Manager.GetString("MsgDisplayNameTooLong", CultureInfo.CurrentUICulture) ?? "MsgDisplayNameTooLong";
    public static string MsgEnterUsername => Manager.GetString("MsgEnterUsername", CultureInfo.CurrentUICulture) ?? "MsgEnterUsername";
    public static string MsgUsernameTooLong => Manager.GetString("MsgUsernameTooLong", CultureInfo.CurrentUICulture) ?? "MsgUsernameTooLong";
    public static string MsgEnterPassword => Manager.GetString("MsgEnterPassword", CultureInfo.CurrentUICulture) ?? "MsgEnterPassword";
    public static string MsgDuplicateAccount => Manager.GetString("MsgDuplicateAccount", CultureInfo.CurrentUICulture) ?? "MsgDuplicateAccount";
    public static string TitleDuplicateAccount => Manager.GetString("TitleDuplicateAccount", CultureInfo.CurrentUICulture) ?? "TitleDuplicateAccount";
    public static string MsgSaveAccountFailed => Manager.GetString("MsgSaveAccountFailed", CultureInfo.CurrentUICulture) ?? "MsgSaveAccountFailed";
    public static string MsgAccountGone => Manager.GetString("MsgAccountGone", CultureInfo.CurrentUICulture) ?? "MsgAccountGone";
    public static string MsgConfirmDelete => Manager.GetString("MsgConfirmDelete", CultureInfo.CurrentUICulture) ?? "MsgConfirmDelete";
    public static string TitleConfirmDelete => Manager.GetString("TitleConfirmDelete", CultureInfo.CurrentUICulture) ?? "TitleConfirmDelete";
    public static string MsgDeleteFailed => Manager.GetString("MsgDeleteFailed", CultureInfo.CurrentUICulture) ?? "MsgDeleteFailed";
    public static string MsgNoEnabledAccounts => Manager.GetString("MsgNoEnabledAccounts", CultureInfo.CurrentUICulture) ?? "MsgNoEnabledAccounts";
    public static string MsgConfirmStartAll => Manager.GetString("MsgConfirmStartAll", CultureInfo.CurrentUICulture) ?? "MsgConfirmStartAll";
    public static string MsgConfirmStopAll => Manager.GetString("MsgConfirmStopAll", CultureInfo.CurrentUICulture) ?? "MsgConfirmStopAll";
    public static string MsgStartFailed => Manager.GetString("MsgStartFailed", CultureInfo.CurrentUICulture) ?? "MsgStartFailed";
    public static string MsgStopFailed => Manager.GetString("MsgStopFailed", CultureInfo.CurrentUICulture) ?? "MsgStopFailed";
    public static string MsgUpdateFailed => Manager.GetString("MsgUpdateFailed", CultureInfo.CurrentUICulture) ?? "MsgUpdateFailed";
    public static string MsgPasswordUpdated => Manager.GetString("MsgPasswordUpdated", CultureInfo.CurrentUICulture) ?? "MsgPasswordUpdated";
    public static string MsgEnterNewPassword => Manager.GetString("MsgEnterNewPassword", CultureInfo.CurrentUICulture) ?? "MsgEnterNewPassword";
    public static string MsgPasswordUpdateFailed => Manager.GetString("MsgPasswordUpdateFailed", CultureInfo.CurrentUICulture) ?? "MsgPasswordUpdateFailed";
    public static string MsgExeNotFound => Manager.GetString("MsgExeNotFound", CultureInfo.CurrentUICulture) ?? "MsgExeNotFound";
    public static string MsgSettingsSaved => Manager.GetString("MsgSettingsSaved", CultureInfo.CurrentUICulture) ?? "MsgSettingsSaved";
    public static string MsgInvalidRoomUrl => Manager.GetString("MsgInvalidRoomUrl", CultureInfo.CurrentUICulture) ?? "MsgInvalidRoomUrl";
    public static string MsgTemplateWarning => Manager.GetString("MsgTemplateWarning", CultureInfo.CurrentUICulture) ?? "MsgTemplateWarning";
    public static string TitleTemplateWarning => Manager.GetString("TitleTemplateWarning", CultureInfo.CurrentUICulture) ?? "TitleTemplateWarning";
    public static string MsgSandboxieMissing => Manager.GetString("MsgSandboxieMissing", CultureInfo.CurrentUICulture) ?? "MsgSandboxieMissing";
    public static string MsgOpenFolderFailed => Manager.GetString("MsgOpenFolderFailed", CultureInfo.CurrentUICulture) ?? "MsgOpenFolderFailed";
    public static string TitleOpenFolder => Manager.GetString("TitleOpenFolder", CultureInfo.CurrentUICulture) ?? "TitleOpenFolder";
    public static string MsgBackupFailed => Manager.GetString("MsgBackupFailed", CultureInfo.CurrentUICulture) ?? "MsgBackupFailed";
    public static string TitleBackup => Manager.GetString("TitleBackup", CultureInfo.CurrentUICulture) ?? "TitleBackup";
    public static string TitleBackupError => Manager.GetString("TitleBackupError", CultureInfo.CurrentUICulture) ?? "TitleBackupError";
    public static string MsgRestoreFailed => Manager.GetString("MsgRestoreFailed", CultureInfo.CurrentUICulture) ?? "MsgRestoreFailed";
    public static string TitleRestore => Manager.GetString("TitleRestore", CultureInfo.CurrentUICulture) ?? "TitleRestore";
    public static string TitleRestoreError => Manager.GetString("TitleRestoreError", CultureInfo.CurrentUICulture) ?? "TitleRestoreError";
    public static string MsgConfirmRestore => Manager.GetString("MsgConfirmRestore", CultureInfo.CurrentUICulture) ?? "MsgConfirmRestore";
    public static string TitleConfirmRestore => Manager.GetString("TitleConfirmRestore", CultureInfo.CurrentUICulture) ?? "TitleConfirmRestore";
    public static string MsgNoLogFile => Manager.GetString("MsgNoLogFile", CultureInfo.CurrentUICulture) ?? "MsgNoLogFile";
    public static string TitleLogs => Manager.GetString("TitleLogs", CultureInfo.CurrentUICulture) ?? "TitleLogs";
    public static string MsgExportLogFailed => Manager.GetString("MsgExportLogFailed", CultureInfo.CurrentUICulture) ?? "MsgExportLogFailed";
    public static string MsgRestartRequired => Manager.GetString("MsgRestartRequired", CultureInfo.CurrentUICulture) ?? "MsgRestartRequired";
    public static string TitleLanguage => Manager.GetString("TitleLanguage", CultureInfo.CurrentUICulture) ?? "TitleLanguage";
    public static string MsgBackupDaysInvalid => Manager.GetString("MsgBackupDaysInvalid", CultureInfo.CurrentUICulture) ?? "MsgBackupDaysInvalid";
    public static string MsgBackupKeepInvalid => Manager.GetString("MsgBackupKeepInvalid", CultureInfo.CurrentUICulture) ?? "MsgBackupKeepInvalid";
    public static string ExeStatusNone => Manager.GetString("ExeStatusNone", CultureInfo.CurrentUICulture) ?? "ExeStatusNone";
    public static string ExeStatusMissing => Manager.GetString("ExeStatusMissing", CultureInfo.CurrentUICulture) ?? "ExeStatusMissing";
    public static string ExeStatusOk => Manager.GetString("ExeStatusOk", CultureInfo.CurrentUICulture) ?? "ExeStatusOk";
    public static string ExeStatusWarn => Manager.GetString("ExeStatusWarn", CultureInfo.CurrentUICulture) ?? "ExeStatusWarn";
    public static string SandboxStatusNone => Manager.GetString("SandboxStatusNone", CultureInfo.CurrentUICulture) ?? "SandboxStatusNone";
    public static string SandboxStatusOk => Manager.GetString("SandboxStatusOk", CultureInfo.CurrentUICulture) ?? "SandboxStatusOk";
    public static string SandboxieAutodetectFail => Manager.GetString("SandboxieAutodetectFail", CultureInfo.CurrentUICulture) ?? "SandboxieAutodetectFail";
    public static string BoxesDone => Manager.GetString("BoxesDone", CultureInfo.CurrentUICulture) ?? "BoxesDone";
    public static string BoxesDoneFailures => Manager.GetString("BoxesDoneFailures", CultureInfo.CurrentUICulture) ?? "BoxesDoneFailures";
    public static string TitleCreateBoxes => Manager.GetString("TitleCreateBoxes", CultureInfo.CurrentUICulture) ?? "TitleCreateBoxes";
    public static string BackupSavedBody => Manager.GetString("BackupSavedBody", CultureInfo.CurrentUICulture) ?? "BackupSavedBody";
    public static string RestoreDoneBody => Manager.GetString("RestoreDoneBody", CultureInfo.CurrentUICulture) ?? "RestoreDoneBody";
    public static string DownloadTitle => Manager.GetString("DownloadTitle", CultureInfo.CurrentUICulture) ?? "DownloadTitle";
    public static string MsgDownloadFailed => Manager.GetString("MsgDownloadFailed", CultureInfo.CurrentUICulture) ?? "MsgDownloadFailed";
    public static string MsgCreateBoxesNoExe => Manager.GetString("MsgCreateBoxesNoExe", CultureInfo.CurrentUICulture) ?? "MsgCreateBoxesNoExe";
    public static string MsgDiagnosticsDone => Manager.GetString("MsgDiagnosticsDone", CultureInfo.CurrentUICulture) ?? "MsgDiagnosticsDone";
    public static string TitleDiagnosticsError => Manager.GetString("TitleDiagnosticsError", CultureInfo.CurrentUICulture) ?? "TitleDiagnosticsError";
    public static string DetailsSelectPrompt => Manager.GetString("DetailsSelectPrompt", CultureInfo.CurrentUICulture) ?? "DetailsSelectPrompt";
    public static string StatusRefreshFailed => Manager.GetString("StatusRefreshFailed", CultureInfo.CurrentUICulture) ?? "StatusRefreshFailed";
    public static string AccountPrefix => Manager.GetString("AccountPrefix", CultureInfo.CurrentUICulture) ?? "AccountPrefix";
    public static string DataPrefix => Manager.GetString("DataPrefix", CultureInfo.CurrentUICulture) ?? "DataPrefix";
    public static string MsgSaveSettingsFailed => Manager.GetString("MsgSaveSettingsFailed", CultureInfo.CurrentUICulture) ?? "MsgSaveSettingsFailed";
    public static string MsgDiagnosticsFailed => Manager.GetString("MsgDiagnosticsFailed", CultureInfo.CurrentUICulture) ?? "MsgDiagnosticsFailed";
    public static string MsgOpenLogFolderFailed => Manager.GetString("MsgOpenLogFolderFailed", CultureInfo.CurrentUICulture) ?? "MsgOpenLogFolderFailed";
    public static string StatusCounts => Manager.GetString("StatusCounts", CultureInfo.CurrentUICulture) ?? "StatusCounts";
    public static string ClientNone => Manager.GetString("ClientNone", CultureInfo.CurrentUICulture) ?? "ClientNone";
    public static string ClientOk => Manager.GetString("ClientOk", CultureInfo.CurrentUICulture) ?? "ClientOk";
    public static string ClientMissing => Manager.GetString("ClientMissing", CultureInfo.CurrentUICulture) ?? "ClientMissing";
    public static string TitleConfirmStartAll => Manager.GetString("TitleConfirmStartAll", CultureInfo.CurrentUICulture) ?? "TitleConfirmStartAll";
    public static string TitleConfirmStopAll => Manager.GetString("TitleConfirmStopAll", CultureInfo.CurrentUICulture) ?? "TitleConfirmStopAll";
    public static string TitleForeignClient => Manager.GetString("TitleForeignClient", CultureInfo.CurrentUICulture) ?? "TitleForeignClient";
    public static string MsgForeignClient => Manager.GetString("MsgForeignClient", CultureInfo.CurrentUICulture) ?? "MsgForeignClient";
    public static string AutoStartAccounts => Manager.GetString("AutoStartAccounts", CultureInfo.CurrentUICulture) ?? "AutoStartAccounts";
    public static string BoxesNone => Manager.GetString("BoxesNone", CultureInfo.CurrentUICulture) ?? "BoxesNone";
    public static string BoxesElevationHint => Manager.GetString("BoxesElevationHint", CultureInfo.CurrentUICulture) ?? "BoxesElevationHint";
    public static string DashboardTitle => Manager.GetString("DashboardTitle", CultureInfo.CurrentUICulture) ?? "DashboardTitle";
    public static string DashboardRunning => Manager.GetString("DashboardRunning", CultureInfo.CurrentUICulture) ?? "DashboardRunning";
    public static string DashboardErrorAcct => Manager.GetString("DashboardErrorAcct", CultureInfo.CurrentUICulture) ?? "DashboardErrorAcct";
    public static string CreateBoxesAdmin => Manager.GetString("CreateBoxesAdmin", CultureInfo.CurrentUICulture) ?? "CreateBoxesAdmin";
    public static string MsgAdminLaunchFailed => Manager.GetString("MsgAdminLaunchFailed", CultureInfo.CurrentUICulture) ?? "MsgAdminLaunchFailed";
    public static string ColPresence => Manager.GetString("ColPresence", CultureInfo.CurrentUICulture) ?? "ColPresence";
    public static string ColRoom => Manager.GetString("ColRoom", CultureInfo.CurrentUICulture) ?? "ColRoom";
}

/// <summary>Formats resource templates. A helper (rather than inline string.Format) because resource
/// templates are resolved per UI culture at runtime and cannot be compile-time constants (CA1863).</summary>
public static class L10n
{
    public static string Fmt(string template, params object?[] args) =>
        string.Format(CultureInfo.CurrentCulture, template, args);
}

